env:
  DIRECTORY: dist
  PROJECT_NAME: json-tool

name: Nightly build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  Build:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.list.outputs.files }}
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: "latest"

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Zip extensions
        run: |
          mkdir -p ${{ env.DIRECTORY }}
          pnpm run zip
          pnpm run zip:firefox
          pnpm run zip:edge
          ls -la ${{ env.DIRECTORY }}  # 调试文件生成

      - name: List files
        id: list
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          files=$(find ${{ env.DIRECTORY }} -type f -name "*.zip" -printf '"%P"\n' | jq -s -c .)
          echo "files=$files" >> $GITHUB_OUTPUT

  Upload:
    needs: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ fromJson(needs.Build.outputs.files) }}
    steps:
      - uses: actions/checkout@v4

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.file }}
          path: ${{ format('{0}/{1}', env.DIRECTORY, matrix.file) }}
