env:
  DIRECTORY: dist
  PROJECT_NAME: json-tool

name: Nightly build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  Version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get version
        id: get_version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
  Build:
    needs: Version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [chrome, edge, firefox]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: "latest"
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Zip extensions
        run: pnpm run zip:${{ matrix.target }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROJECT_NAME }}-${{ needs.Version.outputs.version }}-${{ matrix.target }}
          path: dist/${{ env.PROJECT_NAME }}-${{ needs.Version.outputs.version }}-${{ matrix.target }}.zip
