env:
  DIRECTORY: dist
  PROJECT_NAME: json-tool

name: Nightly build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  Build:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.list.outputs.files }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: "latest"
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Zip extensions
        run: |
          pnpm run zip && 
          pnpm run zip:firefox && 
          pnpm run zip:edge
      - name: List files
        id: list
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          files=$(find ${{ env.DIRECTORY }} -type f -name "${{ env.PROJECT_NAME }}-*.zip" | jq -R . | jq -s -c .)
          echo "files=$files" >> $GITHUB_OUTPUT
        shell: bash

  Upload:
    needs: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ fromJson(needs.Build.outputs.files) }}
    steps:
      - uses: actions/checkout@v4
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          name: all-zip-files
          path: ${{ env.DIRECTORY }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ matrix.file }}
        env:
          ARTIFACT_NAME: $(basename "${{ matrix.file }}")
